In [5]:
import pandas as pd
import numpy as np

In [ ]:

amazon_electronic_df = pd.read_csv('electronics.csv')

In [2]:
amazon_electronic_df

,item_id,user_id,rating,timestamp,model_attr,category,brand,year,user_attr,split
0,0,0,5.0,1999-06-13,Female,Portable Audio & Video,NaN,1999,NaN,0
1,0,1,5.0,1999-06-14,Female,Portable Audio & Video,NaN,1999,NaN,0
2,0,2,3.0,1999-06-17,Female,Portable Audio & Video,NaN,1999,NaN,0
3,0,3,1.0,1999-07-01,Female,Portable Audio & Video,NaN,1999,NaN,0
4,0,4,2.0,1999-07-06,Female,Portable Audio & Video,NaN,1999,NaN,0
...,...,...,...,...,...,...,...,...,...,...
1292949,9478,1157628,1.0,2018-09-26,Female,Headphones,Etre Jeune,2017,NaN,0
1292950,9435,1157629,5.0,2018-09-26,Female,Computers & Accessories,NaN,2017,NaN,0
1292951,9305,1157630,3.0,2018-09-26,Female,Computers & Accessories,NaN,2016,NaN,0
1292952,9303,1157631,5.0,2018-09-29,Male,Headphones,NaN,2018,NaN,0
1292953,9478,1157632,1.0,2018-10-01,Female,Headphones,Etre Jeune,2017,Female,0

In [3]:
amazon_electronic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1292954 entries, 0 to 1292953
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   item_id     1292954 non-null  int64
 1   user_id     1292954 non-null  int64
 2   rating      1292954 non-null  float64
 3   timestamp   1292954 non-null  object
 4   model_attr  1292954 non-null  object
 5   category    1292954 non-null  object
 6   brand       331120 non-null   object
 7   year        1292954 non-null  int64
 8   user_attr   174124 non-null   object
 9   split       1292954 non-null  int64
dtypes: float64(1), int64(4), object(5)
memory usage: 98.6+ MB

In [20]:
cols = ['item_id', 'user_id', 'rating', 'model_attr', 'category', 'brand', 'year']

amazon_electronic_eda_df = amazon_electronic_df[cols]

amazon_electronic_eda_df[cols] = (
    amazon_electronic_eda_df[cols]
        .replace(r'^\s*$', np.nan, regex=True)  # empty or spaces → NaN
        .fillna('Unknown')
)

C:\Users\Ryan\AppData\Local\Temp\ipykernel_2924\3962054384.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_electronic_eda_df[cols] = (

In [21]:
amazon_electronic_eda_df

,item_id,user_id,rating,model_attr,category,brand,year
0,0,0,5.0,Female,Portable Audio & Video,Unknown,1999
1,0,1,5.0,Female,Portable Audio & Video,Unknown,1999
2,0,2,3.0,Female,Portable Audio & Video,Unknown,1999
3,0,3,1.0,Female,Portable Audio & Video,Unknown,1999
4,0,4,2.0,Female,Portable Audio & Video,Unknown,1999
...,...,...,...,...,...,...,...
1292949,9478,1157628,1.0,Female,Headphones,Etre Jeune,2017
1292950,9435,1157629,5.0,Female,Computers & Accessories,Unknown,2017
1292951,9305,1157630,3.0,Female,Computers & Accessories,Unknown,2016
1292952,9303,1157631,5.0,Male,Headphones,Unknown,2018
1292953,9478,1157632,1.0,Female,Headphones,Etre Jeune,2017

In [22]:
amazon_electronic_eda_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1292954 entries, 0 to 1292953
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   item_id     1292954 non-null  int64
 1   user_id     1292954 non-null  int64
 2   rating      1292954 non-null  float64
 3   model_attr  1292954 non-null  object
 4   category    1292954 non-null  object
 5   brand       1292954 non-null  object
 6   year        1292954 non-null  int64
dtypes: float64(1), int64(3), object(3)
memory usage: 69.1+ MB

In [39]:
n = 50000
step = len(amazon_electronic_eda_df)//n
print(step)

amazon_electronic_sample_df = amazon_electronic_eda_df[::step]

25

In [40]:
print(len(amazon_electronic_sample_df))

51719

In [41]:
pivot_table = amazon_electronic_sample_df.pivot_table(index='item_id', columns='user_id', values='rating')

MemoryError: Unable to allocate 2.32 GiB for an array with shape (51390, 6049) and data type float64